import Head from 'next/head'
import styled from "styled-components"

const Hi = styled.h1`
  color: red;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hi>hi</Hi>
    </div>
  )
}
